# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

minimum_pre_commit_version: 2.15.0
exclude: "^$"
fail_fast: true
default_language_version:
  python: python3.8
ci:
  autofix_prs: false

repos:

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.19.0
    hooks:
      - id: validate_manifest

  - repo: meta
    hooks:
      # - id: check-hooks-apply
      - id: check-useless-excludes
      # - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=4096 ]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
#      - id: detect-aws-credentials
      - id: detect-private-key
#      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args: [ --django ]
#      - id: no-commit-to-branch
#        args: [ --branch, staging, --branch, main ]
      - id: pretty-format-json
        args: [ --autofix, --no-ensure-ascii, --no-sort-keys ]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
        exclude: "^(install|get)-poetry.py$"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: "isort (python)"
        types: [ python ]
      - id: isort
        name: "isort (pyi)"
        types: [ pyi ]
        args: [ --lines-after-imports, "-2" ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
#        additional_dependencies: [ flake8-docstrings ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests

# FIXME: file or directory not found: ./tests/
#  - repo: local
#    hooks:
#      - id: run-tests
#        name: run-tests
#        stages: [ manual ]
#        types: [ python ]
#        entry: pytest ./tests/
#        language: python
#        additional_dependencies:
#          - pre-commit
#          - pytest
#        always_run: true
#        pass_filename: false
